.\"------------------------------------------------------------
.\" Id - set Rv,revision, and Dt, Date using rcs-Id tag.
.de Id
.ds Rv \\$3
.ds Dt \\$4
..
.Id $Id: mgstemidxlist.1,v 1.3 1997/01/01 rpap $
.\"------------------------------------------------------------
.TH mgstemidxlist 1 \*(Dt CITRI
.SH NAME
mgstemidxlist \- dumps the stem index file to STDOUT in ASCII format
.SH SYNOPSIS
.B mgstemidxlist
[
.B \-h
]
[
.BI \-d " directory"
]
.B \-s 1|2|3
.BI \-f " name"
.SH DESCRIPTION
.B mgstemidxlist
is a utility program which passes through the stem index and displays
the information.  (This program was used for debugging but is included
for completeness!)  The header information is printed out, then for each
block in the file the block header is displayed.  For each word in the
stem index, the output is formatted as:

.RS
.I number_of_references \*(lqword\*(rq
.br
.RS
.I "->  number_of_cases block 3-in-4_block offset"
.br
.I "->  ..."
.RE
.RE
.SH OPTIONS
Options may appear in any order.
.TP "\w'\fB\-d\fP \fIdirectory\fP'u+2n"
.B \-h
This displays a usage line on
.IR stderr .
.TP
.B -s 1|2|3
The stem index file with the associated stem method.
.br
1 = casefolded and non-stemmed
.br
2 = non-casefolded and stemmed
.br
3 = casefolded and stemmed
.TP
.BI \-d " directory"
This specifies the directory where the document collection can be found.
.TP
.BI \-f " name"
This specifies the base name of the document collection.
.SH ENVIRONMENT
.TP "\w'\fBMGDATA\fP'u+2n"
.SB MGDATA
If this environment variable exists, then its value is used as the
default directory where the
.BR mg (1)
collection files are.  If this variable does not exist, then the
directory \*(lq\fB.\fP\*(rq is used by default.  The command line
option
.BI \-d " directory"
overrides the directory in
.BR MGDATA .
.SH FILES
.TP 25
.B *.invf.dict.blocked.1
Stem index with stem index method 1.
.TP
.B *.invf.dict.blocked.2
Stem index with stem index method 2.
.TP
.B *.invf.dict.blocked.3
Stem index with stem index method 3.
.SH "SEE ALSO"
.na
.BR mg (1),
.BR mg_invf_dict (1),
.BR mg_stem_idx (1).
